export SHELL = bash
export CONFIG_TARGET := arm-linux-gnueabihf
export CONFIG_MODE := arm
export CONFIG_NAME := vexpress
export CONFIG_ABI := aapcs-linux
export CONFIG_CPU := cortex-a9
export CONFIG_FPU := vfpv3-d16
export CONFIG_FLOAT := hard
export CONFIG_LINUX_KERNEL_DEFCONFIG := vexpress
export CONFIG_LINUX_KERNEL_INTREE_DTS_NAME := vexpress-v2p-ca9
export CONFIG_HOSTNAME := clfs-arm
export CONFIG_ROOT_PASSWD := clfs
export CONFIG_LOCAL_TIMEZONE := Asia/Seoul
export CONFIG_PKG_VERSION := CLFS ARM 2017.07
export CONFIG_BUG_URL := https://github.com/LeeKyuHyuk/CLFS-ARM/issues
export CONFIG_PARALLEL_JOBS := $(shell echo `cat /proc/cpuinfo | grep cores | wc -l `)
export CONFIG_STRIP_AND_DELETE_DOCS := 1
export WORKSPACE_DIR := $(shell pwd)
export SOURCES_DIR := $(WORKSPACE_DIR)/sources
export SCRIPTS_DIR := $(WORKSPACE_DIR)/scripts
export SUPPORT_DIR := $(WORKSPACE_DIR)/support
export OUTPUT_DIR := $(WORKSPACE_DIR)/out
export BUILD_DIR := $(OUTPUT_DIR)/build
export TOOLS_DIR := $(OUTPUT_DIR)/tools
export KERNEL_DIR := $(OUTPUT_DIR)/kernel
export ROOTFS_DIR := $(OUTPUT_DIR)/rootfs
export IMAGES_DIR := $(OUTPUT_DIR)/images
export SYSROOT_DIR := $(TOOLS_DIR)/usr/$(CONFIG_TARGET)/sysroot
export PATH := "$(TOOLS_DIR)/bin:$(TOOLS_DIR)/sbin:$(TOOLS_DIR)/usr/bin:$(TOOLS_DIR)/usr/sbin:/sbin:/usr/sbin:$(PATH)"
export EXTRACT := $(SCRIPTS_DIR)/extract.sh
export STEP := $(SCRIPTS_DIR)/step.sh
export SUCCESS := $(SCRIPTS_DIR)/success.sh
export ERROR := $(SCRIPTS_DIR)/error.sh
