export SHELL = bash
export CONFIG_HOSTNAME := clfs-arm
export CONFIG_ROOT_PASSWD := clfs
export CONFIG_LOCAL_TIMEZONE := Asia/Seoul
export CONFIG_PKG_VERSION := CLFS ARM 2017.10
export CONFIG_BUG_URL := https://github.com/LeeKyuHyuk/clfs-arm/issues
export CONFIG_PARALLEL_JOBS := $(shell echo `cat /proc/cpuinfo | grep cores | wc -l `)
export WORKSPACE_DIR := $(shell pwd)
export CONFIG_DIR := $(WORKSPACE_DIR)/config
export DEVICE_DIR := $(WORKSPACE_DIR)/device
export PACKAGES_DIR := $(WORKSPACE_DIR)/packages
export SOURCES_DIR := $(WORKSPACE_DIR)/sources
export SCRIPTS_DIR := $(WORKSPACE_DIR)/scripts
export SUPPORT_DIR := $(WORKSPACE_DIR)/support
export OUTPUT_DIR := $(WORKSPACE_DIR)/out
export TOOLCHAIN_DEPENDENCIES := $(WORKSPACE_DIR)/.toolchain.packages
export SYSTEM_DEPENDENCIES := $(WORKSPACE_DIR)/.system.packages
export BUILD_DIR := $(OUTPUT_DIR)/build
export TOOLS_DIR := $(OUTPUT_DIR)/tools
export ROOTFS_DIR := $(OUTPUT_DIR)/rootfs
export IMAGES_DIR := $(OUTPUT_DIR)/images
export KERNEL_DIR := $(OUTPUT_DIR)/kernel
export PATH := "$(TOOLS_DIR)/bin:$(TOOLS_DIR)/sbin:$(TOOLS_DIR)/usr/bin:$(TOOLS_DIR)/usr/sbin:/sbin:/usr/sbin:$(PATH)"
export EXTRACT := $(SCRIPTS_DIR)/extract.sh
export STEP := $(SCRIPTS_DIR)/step.sh
export SUCCESS := $(SCRIPTS_DIR)/success.sh
export ERROR := $(SCRIPTS_DIR)/error.sh
export PERL5LIB=$(TOOLS_DIR)/lib/perl
unexport PERL_MM_OPT
