#!/bin/bash
echo -e "\e[1m\e[31m>> Build Settings:\e[0m"
echo -e "\e[1mSHELL:\e[0m $SHELL"
echo -e "\e[1mCONFIG_HOST:\e[0m $(echo ${MACHTYPE} | sed -e 's/-[^-]*/-cross/')"
echo -e "\e[1mCONFIG_TARGET:\e[0m $CONFIG_TARGET"
echo -e "\e[1mCONFIG_HOSTNAME:\e[0m $CONFIG_HOSTNAME"
echo -e "\e[1mCONFIG_ROOT_PASSWD:\e[0m $CONFIG_ROOT_PASSWD"
echo -e "\e[1mCONFIG_LOCAL_TIMEZONE:\e[0m $CONFIG_LOCAL_TIMEZONE"
echo -e "\e[1mCONFIG_PKG_VERSION:\e[0m $CONFIG_PKG_VERSION"
echo -e "\e[1mCONFIG_BUG_URL:\e[0m $CONFIG_BUG_URL"
echo -e "\e[1mCONFIG_PARALLEL_JOBS:\e[0m $CONFIG_PARALLEL_JOBS"
echo -e "\e[1mWORKSPACE_DIR:\e[0m $WORKSPACE_DIR"
echo -e "\e[1mCONFIG_DIR:\e[0m $CONFIG_DIR"
echo -e "\e[1mDEVICE_DIR:\e[0m $DEVICE_DIR"
echo -e "\e[1mPACKAGES_DIR:\e[0m $PACKAGES_DIR"
echo -e "\e[1mSOURCES_DIR:\e[0m $SOURCES_DIR"
echo -e "\e[1mSCRIPTS_DIR:\e[0m $SCRIPTS_DIR"
echo -e "\e[1mOUTPUT_DIR:\e[0m $OUTPUT_DIR"
echo -e "\e[1mBUILD_DIR:\e[0m $BUILD_DIR"
echo -e "\e[1mTOOLS_DIR:\e[0m $TOOLS_DIR"
echo -e "\e[1mKERNEL_DIR:\e[0m $KERNEL_DIR"
echo -e "\e[1mROOTFS_DIR:\e[0m $ROOTFS_DIR"
echo -e "\e[1mIMAGES_DIR:\e[0m $IMAGES_DIR"
echo -e "\e[1mSYSROOT_DIR:\e[0m $SYSROOT_DIR"
echo -e "\e[1mPATH:\e[0m $PATH"
echo
echo -e "\e[1m\e[31m>> Device Settings:\e[0m"
echo -e "\e[1mCONFIG_NAME:\e[0m $CONFIG_NAME"
echo -e "\e[1mCONFIG_ABI:\e[0m $CONFIG_ABI"
echo -e "\e[1mCONFIG_CPU:\e[0m $CONFIG_CPU"
echo -e "\e[1mCONFIG_FPU:\e[0m $CONFIG_FPU"
echo -e "\e[1mCONFIG_FLOAT:\e[0m $CONFIG_FLOAT"
echo -e "\e[1mCONFIG_MODE:\e[0m $CONFIG_MODE"
echo -e "\e[1mCONFIG_LINUX_KERNEL_SOURCE:\e[0m $CONFIG_LINUX_KERNEL_SOURCE"
echo -e "\e[1mCONFIG_LINUX_KERNEL_SOURCE_URL:\e[0m $CONFIG_LINUX_KERNEL_SOURCE_URL"
echo -e "\e[1mCONFIG_LINUX_KERNEL_SOURCE_MD5:\e[0m $CONFIG_LINUX_KERNEL_SOURCE_MD5"
echo -e "\e[1mCONFIG_LINUX_KERNEL_DEFCONFIG:\e[0m $CONFIG_LINUX_KERNEL_DEFCONFIG"
echo -e "\e[1mCONFIG_LINUX_KERNEL_INTREE_DTS_NAME:\e[0m $CONFIG_LINUX_KERNEL_INTREE_DTS_NAME"
echo -e "\e[1mCONFIG_IMAGE_SCRIPT:\e[0m $CONFIG_IMAGE_SCRIPT"
